---
title: "Hypothetical clinical trial proposal"
output: html_document
---

This was the course project for Introduction to RCT course(spring 2019). It was an individual assignment requiring each student to identify a promising clinical intervention and draft a proposal for a hypothetical NIH Phase III, two-parallel-group randomized clinical trial to evaluate its efficacy. For my proposal, I selected a promising experimental drug, LY3298176, which was being developed for the treatment of type 2 diabetes. At the time, [LY3298176 had just completed Phase II trials, showing encouraging results](https://www.thelancet.com/journals/lancet/article/PIIS0140-6736(18)32260-8/fulltext). In the proposal, I addressed key issues related to randomized clinical trials: safety, outcome variables, hypothesis formulation, power, stopping rules, etc. The proposal is linked down below.

* [LY3298176 VERSUS DULAGLUTIDE IN TYPE 2 DIABETES MELLITUS TREATMENT (LDT2DM)](.\\files\\Final_Proposal_Haoran.pdf)

Excitingly, LY3298176 is now widely recognized as the phenomenal drug [*tirzepatide*](https://en.wikipedia.org/wiki/Tirzepatide)! It has been approved by the FDA for the treatment of type 2 diabetes and for weight management. Witnessing its transformation—from an experimental drug known to a small group of scientists to a globally celebrated medicine that improves the quality of life for people worldwide—has been truly inspiring. This journey has deepened my passion for drug development, and I look forward to contributing meaningfully to this field in the future.